/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface TurnTouch {
    'connect': () => Promise<void>;
    'onLeft': Function;
    'onRight': Function;
  }
  interface TurnTouchAttributes extends StencilHTMLAttributes {
    'onButtonPress'?: (event: CustomEvent) => void;
    'onLeft'?: Function;
    'onRight'?: Function;
  }
}

declare global {
  interface StencilElementInterfaces {
    'TurnTouch': Components.TurnTouch;
  }

  interface StencilIntrinsicElements {
    'turn-touch': Components.TurnTouchAttributes;
  }


  interface HTMLTurnTouchElement extends Components.TurnTouch, HTMLStencilElement {}
  var HTMLTurnTouchElement: {
    prototype: HTMLTurnTouchElement;
    new (): HTMLTurnTouchElement;
  };

  interface HTMLElementTagNameMap {
    'turn-touch': HTMLTurnTouchElement
  }

  interface ElementTagNameMap {
    'turn-touch': HTMLTurnTouchElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
