/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface TurnTouch {
    'connect': () => Promise<void>;
    'onLeft': Function;
    'onRight': Function;
  }
}

declare namespace LocalJSX {
  interface TurnTouch extends JSXBase.HTMLAttributes {
    'onButtonPress'?: (event: CustomEvent<any>) => void;
    'onLeft'?: Function;
    'onRight'?: Function;
  }

  interface ElementInterfaces {
    'TurnTouch': Components.TurnTouch;
  }

  interface IntrinsicElements {
    'TurnTouch': LocalJSX.TurnTouch;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLTurnTouchElement extends Components.TurnTouch, HTMLStencilElement {}
  var HTMLTurnTouchElement: {
    prototype: HTMLTurnTouchElement;
    new (): HTMLTurnTouchElement;
  };
  interface HTMLElementTagNameMap {
    'turn-touch': HTMLTurnTouchElement
  }

  interface ElementTagNameMap {
    'turn-touch': HTMLTurnTouchElement;
  }
}

